
version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./:/home
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8890:8888"
    volumes:
      - ./:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.password='sha1:1d14edeea5dc:b801b0fd63b4225c32bd02d5d48d4d1401cdcf94'
